# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.6.2

package:
  name: markdown-to-confluence
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/markdown-to-confluence/markdown_to_confluence-${{ version }}.tar.gz
  sha256: 15f44e940d5f2894c3e52afce51fc12f8e9d3c9ba341ed971af1bd9de363d8c8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - md2conf = md2conf.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - cattrs >=26.1
    - lxml >=6.1
    - markdown >=3.10
    - orjson >=3.11
    - pymdown-extensions >=11.0
    - pyyaml >=6.0
    - requests >=2.34
    - truststore >=0.10
    - typing_extensions >=4.16
    - pathspec >=1.1
  run_constraints:
    - matplotlib >=3.10

tests:
  - python:
      imports:
        - md2conf
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - md2conf --help

about:
  summary: Publish Markdown files to Confluence wiki
  homepage: https://github.com/hunyadi/md2conf
  repository: https://github.com/hunyadi/md2conf
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
