# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: markdown-to-confluence
  version: "0.4.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/markdown_to_confluence-${{ version }}.tar.gz
  sha256: 9323f602e0d210caed114aacfb54886738cc4b04f00c5d2052467f8fc5a9cb28

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - md2conf = md2conf.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80.0
    - pip
  run:
    - python >=${{ python_min }},<4
    - certifi >=2025.8.3
    - json-strong-typing >=0.3.9
    - lxml >=6.0
    - markdown >=3.8
    - pymdown-extensions >=10.16
    - pyyaml >=6.0
    - requests >=2.32
    - truststore >=0.10
    - typing_extensions >=4.14

tests:
  - python:
      imports:
        - md2conf
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - md2conf --help

about:
  summary: Publish Markdown files to Confluence wiki
  homepage: https://github.com/hunyadi/md2conf
  repository: https://github.com/hunyadi/md2conf
  license: MIT
  license_file: LICENSE


extra:
  recipe-maintainers:
    - rxm7706
